app:
  jolt:
    traineeDetailsPostRequestJoltSpec: /TraineeDetailsPostRequestJoltSpec.json
    traineeDetailsGetResponseJoltSpec: /TraineeDetailsGetResponseJoltSpec.json
    traineeDetailsPostResponseJoltSpec: /TraineeDetailsPostResponseJoltSpec.json
    traineeDetailsPutRequestJoltSpec: /TraineeDetailsPutRequestJoltSpec.json
