app:
  jolt:
    traineeDetailsRequestJoltSpec: /TraineeDetailsRequestJoltSpec.json
    traineeDetailsGetResponseJoltSpec: /TraineeDetailsGetResponseJoltSpec.json
    traineeDetailsPostResponseJoltSpec: /TraineeDetailsPostResponseJoltSpec.json
